name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_URL: 'http://localhost:3333'
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12.18.3'
      - uses: actions/checkout@v2
      - name: Run coverage
        run: |
          npm install
          npm run coverage
      - uses: codecov/codecov-action@v1
        with:
          directory: ./tests/coverage/
